### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by BeyondEvil** [aws/rolesanywhere-credential-helper#100]
Any plans on providing an official docker image with the signer?

The use case is as a sidecar to applications that do not natively support Roles Anywhere (AWS SDK V2).

**Comment by 13ajay** [comment]
Hi, yes, we do plan on eventually providing an official Linux Docker image for x64 and Aarch64. I will get back to you with a timeline on this after discussing with the team.

**Comment by drewhemm** [comment]
In relation to [Connect your on-premises Kubernetes cluster to AWS APIs using IAM Roles Anywhere](https://aws.amazon.com/blogs/security/connect-your-on-premises-kubernetes-cluster-to-aws-apis-using-iam-roles-anywhere/)...

If there was an image in ECR Public, 'Step 3' in the guide would go away completely, and in 'Step 5', the image would reference an existing asset:

```yaml
spec:
  containers:
    - name: iamra-sidecar
        image: 012345678912.dkr.ecr.us-east-2.amazonaws.com/<replace-with-iamra-sidecar-repository> 
```
