### ISSUE TITLE
arm64 binaries

### ISSUE THREAD

**Issue by courtland** [aws/rolesanywhere-credential-helper#56]
Any chance this will/can be released for linux/arm64? We're using it to obtain credentials from IoT and other edge devices running arm64.

**Comment by JamesTGrant** [comment]
Agreed - We have ansible that I'd like to keep rather than having to build ourselves:
```
- name: Download AWS signing helper for Roles Anywhere
  become: yes
  ansible.builtin.get_url:
    url: https://rolesanywhere.amazonaws.com/releases/1.0.4/{{ ansible_architecture | upper }}/{{ Kernel }}/aws_signing_helper
```
